### PR TITLE
Solaris 11.1 -- OpenCSW

### PR DESCRIPTION
**Pull request by jaymell**
Add support for installation using OpenCSW -- assumes you already have OpenCSW repositories enabled

### CODE REVIEW

**Comment by Mooash** [comment]
Awesome, thanks for the addition. You've confirmed this works on Solaris systems? I don't have any to test on myself.

**Comment by jaymell** [comment]
Good question!

So, it worked on the systems I deployed to in my environment. Just to cover
all my bases, I spun up a fresh VM  this morning and am running into
issues. I didn't install the package we use to manage privileged commands
(our equivalent of 'sudo') and did have problems until I removed all the
references to sudo in the tasks and handlers. This kind of goes back to the
issue you asked about previously, so I will do some additional testing to
see if I can work around it without changing the rest of the files in the
role.

But, once I get past the sudo issue and make sure that CSW repositories are
enabled, things work great.  Regarding that latter point (CSW packages),
the role will likely fail if people haven't previously set the repo up, so
I should probably go ahead and add a specific task to enable this
repository if not already done.

I'll get back to you once I've gotten some time do that.

--James

**Comment by Mooash** [comment]
Please feel free to remove the `sudo` dependency as I'm planning on
removing it from the whole role after this merge.

In terms of the repo, could you please set that as a default? It'll make
overriding it easier for people that don't use it, I'm assuming it isn't
the only way to get the package on solaris? I'm assuming some people may
setup internal repos with the package sometimes?

**Comment by jaymell** [comment]
I made an additional commit, adding the installation of CSWpkgutil if not already present on the system. I've verified that it works perfectly on freshly deployed Solaris 11.1 VMs.

Also, I removed all the references to sudo throughout the role and verified that it successfully deploys.

Let me know if this looks good to you, or if you'd like to see any additional changes. I will be out of the country for a few weeks, with only sporadic access to the interwebs, starting next Monday, so it could be a few weeks before you hear from me.

Cheers,
James

**Pull request merged**
